### ISSUE TITLE
Find a good documentation generator

### ISSUE THREAD

**Issue by GMartigny** [pencil-js/pencil.js#28]
Low level documentation could be generated from jsDoc. We need to find a good module able to handle this for each sub-packages.
Generated documentation should be easily readable, display all informations present in jsDoc and have links to other files (for types for example).

PS: High level documentation ("readme", "first steps", "changelog" ...) should still be written by hand.

**Comment by genemars** [comment]
I use a script to convert the jsDoc to JSON, then I have a js function that can parse the JSON and render the API.
The result is this:
https://genielabs.github.io/zuix/#/api
This is the script (gulp):
https://github.com/genielabs/zuix/blob/master/build/gulp/tasks/zuix/dox.js
And this is the js used to parse/render the JSON data. 

Can this be useful for the purpose?

**Comment by GMartigny** [comment]
I'm not planning on using Gulp or any task runner. Too bad that Dox only generate JSON.
Grazie comunque.

**Comment by genemars** [comment]
You don't have to use gulp.
Just use `dox` to generate JSON and then re-use the `api_loader.js` code or write your own code logic to fetch the JSON and render it (either statically or dynamically).

**Comment by GMartigny** [comment]
Fixed by 18fd2326e434603b67f00baec35bda46afcc5d62
