### ISSUE TITLE
Add heart shape

### ISSUE THREAD

**Issue by GMartigny** [pencil-js/pencil.js#4]
We should add the ❤️ shape.

**Comment by zachary-nguyen** [comment]
Mind if I take care of this :) ?

**Comment by GMartigny** [comment]
@zachary-nguyen Absolutely not. We just need to work out what's the required parameters for a heart. I won't mind to start with a simple `radius` parameter and build from there.

This should directly inherit from [`Component`](https://github.com/pencil-js/pencil.js/tree/master/modules/component) and override the `trace` function.

For the draw itself, you could use handmade bezierCurve (maybe the best solution) or use the [`Path`](https://github.com/pencil-js/pencil.js/tree/master/modules/path) class (easiest solution).

If you have any question, please ask.

**Comment by zachary-nguyen** [comment]
@GMartigny 
I went ahead and started before here's what I have so far using bezierCurves from extending the Path class. All the values are hard coded for now, but I think as you said a simple radius parameter with maybe a size param would suffice?
![image](https://user-images.githubusercontent.com/43250829/64914021-9d508e80-d718-11e9-8f00-7bec67cb18e6.png)

**Comment by GMartigny** [comment]
Not sure this new class should extends `Path` as there is some useless function for a heart. However, it could use `Path` as a dependency.

This already looks good in my opinion !

**Comment by zachary-nguyen** [comment]
Awesome! You're right, I'll just import the bezier function from Path and that should be enough. I'll keep you posted with progress :)

**Comment by GMartigny** [comment]
Can't wait =)
Open a PR as soon as you want so we can discuss about the actual code.

**Comment by GMartigny** [comment]
Fixed by #61 🎉
