### ISSUE TITLE
Draggable cursor not correctly updated

### ISSUE THREAD

**Issue by GMartigny** [pencil-js/pencil.js#57]
#### Information

 - Your current navigator: Chrome v73
 - The package and version you used: @pencil.js/draggable v1.6.3

#### Description

When setting a component draggable, the cursor option change to `"grab"` => ok. But when the component is actively dragged, the cursor should change to `"grabbing"` => ko.
The Scene `setCursor` function seems not to be called with the updated option.

#### Reproduce by

```js
const square = new Square(scene.center, 200);
square.draggable();
scene.add(square);
```
Grabbing the square doesn't update the cursor.

**Comment by zachary-nguyen** [comment]
I can take a look a this one and make a PR if I can reproduce :)

**Comment by zachary-nguyen** [comment]
Seems to me like its working as intended on Chrome v73 aswell.

**Comment by GMartigny** [comment]
I can only reproduce when the debug console is open and I have no idea why 🤔.
Thanks for the review, I'll close this issue but there's still a weird behavior somewhere...
