### ISSUE TITLE
Polish the Heart component

### ISSUE THREAD

**Issue by GMartigny** [pencil-js/pencil.js#62]
#### Information 
 - The package and version you used: @pencil.js/polygon v1.11.0

#### Description 

A few things was missing from the first implementation of the Heart component.

 - [ ] The trace function doesn't take into account the heart position (`this.position`)
 - [ ] The `radius` is not representative of the actual radius.
 - [ ] The `static from` function is missing
 - [ ] Missing link in the main Pencil.js readme.md

#### Reproduce by 
```js
// The heart won't be at the center neither will have a radius of 100px
const heart = new Heart(scene.center, 100, {
	fill: "red",
});
// missing function
const clone = Heart.from(heart.toJSON());
```

**Comment by zachary-nguyen** [comment]
You can assign it to me I already started progress and just finishing up :)

**Comment by zachary-nguyen** [comment]
@GMartigny I'm trying to think of a way to use the radius appropriately with the bezier curve. As of right now, radius is more of a ratio. But since the heart isn't circular/ellipse I can't really use a uniform radius. Also, we want the heart shape's center position to be located at the starting point correct?

**Comment by GMartigny** [comment]
> But since the heart isn't circular/ellipse I can't really use a uniform radius

Well if we're going to call that param radius, let's use it like that.

![heart](https://user-images.githubusercontent.com/2543511/65085594-eb7ebf80-d9ae-11e9-92ec-b54cb81125e2.png)

Here you can see a blue circle and a red heart with the same radius (note that the tip and side of the heart are at 1 radius). However, the top notch (pun not intended) is at about 1/3 radius.
The black dot mark the center of both shapes.
Here the code for that (not working at the moment)

```js
const heart = new P.Heart(scene.center, 100, {
    fill: "red",
});

const circle = new P.Circle(heart.position, heart.radius, {
    fill: "blue",
});

const center = new P.Circle(circle.position, 4);

scene.add(circle, heart, center).render();
```

Know that `Component` already move to the position of any shape (the black dot). So, you'll need to move up a bit and then start your curve.
Does that clear everything up ?

**Comment by zachary-nguyen** [comment]
@GMartigny 
Yep, that's perfect thanks!

**Comment by GMartigny** [comment]
Hi @zachary-nguyen,
Still willing to do this ? I'm looking forwards to publish a new version with the Heart component.

**Comment by zachary-nguyen** [comment]
@GMartigny 
Yep! Sorry got caught up in work and other projects :) I'll jump back in shortly sorry for the wait!

**Comment by zachary-nguyen** [comment]
@GMartigny 
As of right now I have the heart sitting like this 
![image](https://user-images.githubusercontent.com/43250829/65822782-25a25980-e218-11e9-9221-0c79327f5a07.png)
Do you want me to move the heart center up so the bottom touches as well?
