### ISSUE TITLE
Impossible to install v2.0.0

### ISSUE THREAD

**Issue by GMartigny** [pencil-js/pencil.js#77]
While installing Pencil.js@2.0.0, an error occur.

	$ npm install pencil.js@2.0.0
	npm ERR! code ENOLOCAL
	npm ERR! Could not install from "node_modules\pencil.js\src\modules\arc" as it does not contain a package.json file.

This is related to the issue https://github.com/npm/cli/issues/1756 and https://github.com/npm/pacote/issues/51.

**Comment by suspiciousfellow** [comment]
Also encountering this - a shame cause looked perfect for our use case...

**Comment by suspiciousfellow** [comment]
(am working around this temporarily to experiment with it, but we would need this fixed to ship I think)

**Comment by GMartigny** [comment]
This can also be avoided by using `npm@7`.
