### ISSUE TITLE
Document Scene's first parameter: parent

### ISSUE THREAD

**Issue by Marr11317** [pencil-js/pencil.js#79]
Hello there,
This is not code related (even if at the end it falls to that).

When looking at the library, I had a hard time understanding how to use the Scene element without having my whole webpage as a canvas. When I looked at the website code, it only showed how to use the div's `data-script` attribute, which is not convenient for many use cases.

I finally found out that the answer was to use the scene first parameter, which is not described anywhere in the docs, except in [this code example](https://github.com/pencil-js/pencil.js/tree/master/src/modules/scene#examples). The example gives no info about it.

This of course relates to #28: find a good docs generator.

**Comment by GMartigny** [comment]
Thanks for the report.
Indeed documentation is not the best right now. You can find some informations on the [Guide's Scene section](https://pencil.js.org/guide/#scene).
But, sure thing to do is resolve #28 and auto-generate a thorough documentation.

**Comment by GMartigny** [comment]
I'm still working on it, but you should find everything you need in [the documentation](https://docs.pencil-js.vercel.app/module-Scene.html).

**Comment by Marr11317** [comment]
Looks good! Thanks!
