### ISSUE TITLE
Documentation doesn't appear to have any function descriptions

### ISSUE THREAD

**Issue by nergmada** [pencil-js/pencil.js#81]
#### Information 
 - Your current navigator: Chrome v86
 - N/A

#### Description 
I've been trying to use the documentation, but a lot of core functions particularly around scene, container, line and rectangle all seem to be missing function descriptions. Is the documentation out of data on the vercel deployment?

For example, on the Line documentation, although it says that it takes a `new Line(startpoint, ...points, options)` the additional points aren't really points at all but vectors, (e.g. they're points relative to the initial point). 

It would be useful if there was a function description for this to make that more clear, because the argument types alone are somewhat misleading (I get why you'd reuse a pre-defined 2D point for additional points, but they behave like vectors, so there should be some kind of health warning in there).

#### Reproduce by 
N/A

**Comment by GMartigny** [comment]
Thanks for the report. The documentation is quite new and still far from perfect.

In the example of the [Line constructor](https://docs.pencil-js.vercel.app/module-Line.html#module:Line), there is a description for the points (that is "List of points", which is not that helpful).
I'll try to add informations to all descriptions. In the mean time, could you point me to where you find that it's critically missing informations ?

**Comment by nergmada** [comment]
I mean, to be honest, I'd be more than happy to help add descriptions as I'm using the library where I can. If you're okay with me asking questions here, I'll fork the repo and add description the JSDocs as I go.

Also, I don't think the `absolute: true` flag works for absolute positioning of points in the line. I'm using version 1.18.0 of pencil

**Comment by nergmada** [comment]
So it seems that a reason some features are not working as expected is because the documentation is related to the master branch, whilst the npm code is based on the latest tag version. 

Meaning for example, the `absolute` flag that is shown in the documentation isn't actually available in v2.0.0 because it's something that's been added afterwards and documented

**Comment by GMartigny** [comment]
> If you're okay with me asking questions here, I'll fork the repo and add description the JSDocs as I go.

I'll be more than happy for you to help me on this. Please, make a PR and submit your suggestion.

> So it seems that a reason some features are not working as expected is because the documentation is related to the master branch, whilst the npm code is based on the latest tag version.

You put your finger on something I didn't consider. It's not be a good idea to have the documentation be on `master`. I'll look into this.

**Comment by nergmada** [comment]
It might be better because there's currently an outstanding recommendation to use pencil 1.18.0 if running npm <7, to have documentation that allows you to select the version of pencil you're using. Is there a way to generate documentation for each version tag maybe?

**Comment by GMartigny** [comment]
> Is there a way to generate documentation for each version tag maybe?

That's would be the best solution, but I'm not sure this is possible given my current setup. Pencil.js has 52 releases to this date, and I don't want to build docs for each of them. Maybe only one for each major release.

**Comment by GMartigny** [comment]
I fixed the documentation building process. Now, it will only update documentation on new Pencil.js versions.
This change will be triggered in the next version landing as soon as https://github.com/webpack/webpack/issues/2933 is resolved.

We still need to work on better explanation in jsdoc. Are you still up to do it ?
