### ISSUE TITLE
Provide typescript types

### ISSUE THREAD

**Issue by Marr11317** [pencil-js/pencil.js#88]
This library does not provide typescript declaration files. Is there any chance it ever will?

It should be as simple as installing the typescript compiler (tsc) and running `tsc src/**/*.js --declaration --allowJs --emitDeclarationOnly --outDir types` and adding a reference to the types in package.json.

**Comment by GMartigny** [comment]
This is a good idea.

Can `tsc` infer types definition from pure Javascript ?

**Comment by Marr11317** [comment]
Yes it can, see https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Comment by GMartigny** [comment]
Fixed by #89
