### ISSUE TITLE
Samples broken

### ISSUE THREAD

**Issue by stefnotch** [pencil-js/pencil.js#92]
#### Information 
 - Your current navigator: Firefox 87 and Microsoft Edge Version 89.0.774.77
 - The package and version you used: https://pencil.js.org/

#### Description 

I visited the neat looking homepage only to find white spaces where the beautiful pencil.js demos should have been.

![image](https://user-images.githubusercontent.com/10220080/115183336-e1b5c480-a0db-11eb-83d6-5b77c2d57a08.png)

This is what the browser console has to say regarding that matter
![image](https://user-images.githubusercontent.com/10220080/115183430-090c9180-a0dc-11eb-9e40-3ec2852cfec8.png)

#### Reproduce by 

https://codepen.io/GMartigny/pen/zYGargv?editors=0010

**Comment by GMartigny** [comment]
Hi, this is finally fixed in https://github.com/pencil-js/pencil.js/releases/tag/v2.3.0 ✌
