### ISSUE TITLE
Broken type definitions

### ISSUE THREAD

**Issue by stefnotch** [pencil-js/pencil.js#93]
#### Information 
 - Your current navigator: Firefox 87
 - The package and version you used: pencil.js v2.1.0
 - NPM version: 7.0.15

#### Description 

I installed this library using `npm i pencil.js`.
Then I imported some basic stuff
```ts
import { Scene, Triangle } from "pencil.js";
```
And then I tried using the triangle, however the Typescript definitions mostly didn't work. It seems like this is causing it
![image](https://user-images.githubusercontent.com/10220080/115186291-bcc45000-a0e1-11eb-84fe-28d3e251d7fd.png)

**Comment by GMartigny** [comment]
Hi,

This is the same cause as #92. However, this issue is more concerning since it breaks real life usage (not only examples).

If you're using a bundler (eg webpack), here's the current quickfix to avoid this:

```js
import { Scene, Triangle } from "pencil.js/src";
```

I'm actively working to fix this problem as soon as possible.

**Comment by GMartigny** [comment]
Hi,
This should be fixed in https://github.com/pencil-js/pencil.js/releases/tag/v2.3.0 😎
